# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Aug 18 19:12:44 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(490, 343)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        self.label_ui_id = QtGui.QLabel(self.tab)
        self.label_ui_id.setObjectName(_fromUtf8("label_ui_id"))
        self.gridLayout_2.addWidget(self.label_ui_id, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 0, 1, 2)
        self.label_tlabel = QtGui.QLabel(self.tab)
        self.label_tlabel.setObjectName(_fromUtf8("label_tlabel"))
        self.gridLayout_2.addWidget(self.label_tlabel, 4, 0, 1, 1)
        self.label_ui_options_header = QtGui.QLabel(self.tab)
        self.label_ui_options_header.setMaximumSize(QtCore.QSize(450, 132))
        self.label_ui_options_header.setObjectName(_fromUtf8("label_ui_options_header"))
        self.gridLayout_2.addWidget(self.label_ui_options_header, 0, 0, 1, 3)
        self.button_t_set_label = QtGui.QPushButton(self.tab)
        self.button_t_set_label.setMinimumSize(QtCore.QSize(150, 0))
        self.button_t_set_label.setObjectName(_fromUtf8("button_t_set_label"))
        self.gridLayout_2.addWidget(self.button_t_set_label, 5, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 3, 1, 1)
        self.label_tid = QtGui.QLabel(self.tab)
        self.label_tid.setObjectName(_fromUtf8("label_tid"))
        self.gridLayout_2.addWidget(self.label_tid, 2, 3, 1, 3)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 6)
        self.line_edit_tlabel = QtGui.QLineEdit(self.tab)
        self.line_edit_tlabel.setObjectName(_fromUtf8("line_edit_tlabel"))
        self.gridLayout_2.addWidget(self.line_edit_tlabel, 5, 0, 1, 4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.button_restore_xprv = QtGui.QPushButton(self.tab_2)
        self.button_restore_xprv.setObjectName(_fromUtf8("button_restore_xprv"))
        self.gridLayout_3.addWidget(self.button_restore_xprv, 5, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 1, 0, 1, 2)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.button_wipe = QtGui.QPushButton(self.tab_2)
        self.button_wipe.setObjectName(_fromUtf8("button_wipe"))
        self.gridLayout_3.addWidget(self.button_wipe, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.button_new_keys_128 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_new_keys_128.sizePolicy().hasHeightForWidth())
        self.button_new_keys_128.setSizePolicy(sizePolicy)
        self.button_new_keys_128.setMinimumSize(QtCore.QSize(40, 0))
        self.button_new_keys_128.setObjectName(_fromUtf8("button_new_keys_128"))
        self.horizontalLayout.addWidget(self.button_new_keys_128)
        self.button_new_keys_192 = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_new_keys_192.sizePolicy().hasHeightForWidth())
        self.button_new_keys_192.setSizePolicy(sizePolicy)
        self.button_new_keys_192.setMinimumSize(QtCore.QSize(40, 0))
        self.button_new_keys_192.setObjectName(_fromUtf8("button_new_keys_192"))
        self.horizontalLayout.addWidget(self.button_new_keys_192)
        self.button_new_keys_256 = QtGui.QPushButton(self.tab_2)
        self.button_new_keys_256.setMinimumSize(QtCore.QSize(40, 0))
        self.button_new_keys_256.setObjectName(_fromUtf8("button_new_keys_256"))
        self.horizontalLayout.addWidget(self.button_new_keys_256)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 3, 0, 1, 2)
        self.text_xprv = QtGui.QPlainTextEdit(self.tab_2)
        self.text_xprv.setObjectName(_fromUtf8("text_xprv"))
        self.gridLayout_3.addWidget(self.text_xprv, 5, 0, 1, 1)
        self.text_mnemonic = QtGui.QPlainTextEdit(self.tab_2)
        self.text_mnemonic.setObjectName(_fromUtf8("text_mnemonic"))
        self.gridLayout_3.addWidget(self.text_mnemonic, 4, 0, 1, 1)
        self.button_restore_mnemonic = QtGui.QPushButton(self.tab_2)
        self.button_restore_mnemonic.setObjectName(_fromUtf8("button_restore_mnemonic"))
        self.gridLayout_3.addWidget(self.button_restore_mnemonic, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_about = QtGui.QWidget()
        self.tab_about.setObjectName(_fromUtf8("tab_about"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_about)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_about)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_5.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_about, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Trezor Toolkit", None))
        self.label_ui_id.setText(_translate("MainWindow", "ID:", None))
        self.label_tlabel.setText(_translate("MainWindow", "Label:", None))
        self.label_ui_options_header.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Trezor Options</span></p></body></html>", None))
        self.button_t_set_label.setText(_translate("MainWindow", "Update", None))
        self.label_tid.setText(_translate("MainWindow", "(Set at runtime)0000000000", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "General", None))
        self.button_restore_xprv.setText(_translate("MainWindow", "Restore from BIP32 xprv", None))
        self.label.setText(_translate("MainWindow", "WIPE - DANGEROUS", None))
        self.button_wipe.setText(_translate("MainWindow", "Wipe - DANGER DANGER", None))
        self.label_2.setText(_translate("MainWindow", "Generate new seed and load:", None))
        self.label_3.setText(_translate("MainWindow", "Entropy (bits):", None))
        self.button_new_keys_128.setText(_translate("MainWindow", "128", None))
        self.button_new_keys_192.setText(_translate("MainWindow", "192", None))
        self.button_new_keys_256.setText(_translate("MainWindow", "256", None))
        self.text_xprv.setPlainText(_translate("MainWindow", "XPRV HERE", None))
        self.text_mnemonic.setPlainText(_translate("MainWindow", "MNEMONIC HERE", None))
        self.button_restore_mnemonic.setText(_translate("MainWindow", "Restore From Mnemonic", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Wipe / Reset", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Created by Max Kaye (XertroV, https://xk.io)\n"
"of Eudemonia Research (http://eudemonia.io)\n"
"\n"
"All code (besides a bit borrowed from Electrum) is public domain where possible.\n"
"\n"
"No implied warranty is included with this software, if you break your Trezor, lose money, whatever, it\'s on you.\n"
"\n"
"Other Authors:\n"
"(none thus far)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_about), _translate("MainWindow", "About", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

